### PR TITLE
Added a Save / Load button

### PR DESCRIPTION
**Pull request by phecdaDia**
Added the ability to save and load addresses to / from a *.xml file. This file is currently named after the process name shown in the Processes Combobox.  
Further adjustments might be needed since I had troubles connection to my 3ds ( local issues ) so I couldn't test this extensively just yet.

### CODE REVIEW

**Comment by aldelaro5** [comment]
I actually figured out how to build with mono develop and apply commit to a local branch so I went ahead and did some tests.

Save seems to work perfectly, I had 2 4byte addresses and 3 float pointer addresses and they successfully saved into the xml file.

Load however almost works.  I got a crash and after little debugging, I found out that the problem is likely because it couldn’t resolve the pointer into its value.  I tried to comment out the 2 lines that sets the value column and everything loaded perfectly.  I also tried removing the pointers addresses in the xml and uncomment those lines, everything loaded including the value column.  

Other than that, no issue.

**Comment by valarnin** [comment]
Looking into merging this PR now. If everything pans out I'll release an 0.8.6 version with this support today.

**Comment by valarnin** [comment]
Merged this PR. Need to add some additional sanity checks before releasing.

**Comment by valarnin** [comment]
v0.8.6.0-beta released with changes from this PR. Thanks, @aldelaro5 for the request and @imthe666st for the initial implementation.

**Pull request merged**
