### PR TITLE
Some little changes - see commit messages for details

### PR DESCRIPTION
**Pull request by f-israel**
Containing:
- MemoryViewer/-Editor
- some exception handlers
- name column
- JSON saving
- memory range caching
- ...

### CODE REVIEW

**Review by valarnin — COMMENTED** [review]
Currently reviewing. If everything looks good I'll pull this down and build tonight, make sure it runs from a clean environment.

**Review by valarnin — CHANGES_REQUESTED** [review]
You seem to be utilizing some C# 6.0 features \(see [Forms/MemoryViewer.cs, line 119](https://github.com/f-israel/NTRRemoteDebugger/blob/78547b1951831914f827555b52da3a2dc2b32ee1/NTRDebuggerTool/Forms/MemoryViewer.cs#L28)), which are not supported in VS2012, which is the version of VS that I use. I'm not sure if you want to change to using C# 5.0 or lower features, or instead add the Microsoft.Net.Compilers nuget package and get it to force compilation using 6.0. Either way, I can't test this as it currently stands unfortunately.

**Comment by f-israel** [comment]
Set my language version to be 5.0 and fixed the lines. Maybe it's possible to update to at least 6.0 (Mono supported) in future? Btw: VS2012 is quite old. Why not using VS2017 Comm. in parallel?

**Comment by f-israel** [comment]
Some changes regarding accepting/declining?
Would be interesting if I met the requirements now. :)

**Comment by valarnin** [comment]
No issues compiling this time. I don't have my 3DS handy to test with at the moment, but I'll pull these into Master.

**Comment by valarnin** [comment]
As a side note, I have no clue why I didn't get a notification for your changes on June 25th, thanks for pinging me on this again.

**Pull request merged**
